### ISSUE TITLE
whole screen is not used 

### ISSUE THREAD

**Issue by RaWolFoX** [cyb3rko/Secure-Photo-Viewer#1]
Can you make it full screen. Its not using whole screen. Status bar is hiding but that area is not used. There is a black bar on top side.

![look here](https://github.com/gregordr/Secure-Photo-Viewer/assets/114433842/8531d682-e786-4571-8f56-0d94cac7a2f8)

**Comment by cyb3rko** [comment]
I will try to tackle that 👍🏻

**Comment by RaWolFoX** [comment]
> I will try to tackle that 👍🏻

Ok.👍🏻👍🏻

**Comment by RaWolFoX** [comment]
> I will try to tackle that 👍🏻

any updates?🙂

**Comment by RaWolFoX** [comment]
Hey 🙂

**Comment by cyb3rko** [comment]
Can you check out [Version 2.0.1](https://github.com/cyb3rko/Secure-Photo-Viewer/releases/tag/v2.0.1)?  
Should be improved now.

**Comment by RaWolFoX** [comment]
> Can you check out [Version 2.0.1](https://github.com/cyb3rko/Secure-Photo-Viewer/releases/tag/v2.0.1)?  
> Should be improved now.

Ok. I will check when im free.😍

**Comment by RaWolFoX** [comment]
> Can you check out [Version 2.0.1](https://github.com/cyb3rko/Secure-Photo-Viewer/releases/tag/v2.0.1)?  
> Should be improved now.

Working fine...good mate👍🏻👍🏻
